---
title: "Preprocessing for MA Thesis"
author: Kagen Lim
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Loading Data In}
#setting up my dataset#
library(haven)
library(psych)
library(tibble)
library(dplyr)

df <- read_sav("pu_ssocs18.sav") #2017-2018 School Survey on Crime and Safety Dataset; find the hyperlink above#
```

##Basic Model
```{r Basic Model}
#update#
basic_model <- df[, c("INCID18", "C0532", "C0534", "C0536")]

colnames(basic_model) <- c("total_incidents", "percentlowgrades", "percentgocollege", "percentacadimpt")

basic_model <- na.omit(basic_model) #making sure that no NA values remain#

checkzero_total_incidents <- basic_model$total_incidents == 0
table(checkzero_total_incidents) #there are 274 schools with zero incidents, out of all 2762 schools#

checkzero_percentlowgrades <- basic_model$percentlowgrades == 0
table(checkzero_percentlowgrades)#there are 128 schools with 0% low grades, out of all 2762 schools#

checkzero_percentgocollege <- basic_model$percentgocollege== 0
table(checkzero_percentgocollege)

checkzero_percentacadimpt <- basic_model$percentacadimpt== 0
table(checkzero_percentgocollege)

#These are all non-zero numbers, so log1p transformation will be necessary#

basic_model$percentnogocollege = 100 - basic_model$percentgocollege #reverse-recoding percentgocollege as percent no go college#

describe(basic_model$percentgocollege) #checking recoding#
describe(basic_model$percentnogocollege) #checking recoding#

basic_model$percentacadnotimpt = 100 - basic_model$percentacadimpt #reverse-recoding percent acadnotimpt as percentacadimpt#

describe(basic_model$percentacadimpt) #checking recoding#
describe(basic_model$percentacadnotimpt) #checking recoding#

basic_model$total_incidentslog1p = log1p(basic_model$total_incidents)

basic_model$percentlowgradeslog1p = log1p(basic_model$percentlowgrades)

basic_model$percentnogocollegelog1p = log1p(basic_model$percentnogocollege)

basic_model$percentacadnotimptlog1p = log1p(basic_model$percentacadnotimpt)

basic_model = select(basic_model, -c(total_incidents, percentgocollege,percentnogocollege, percentacadimpt, percentacadnotimpt, percentlowgrades))

cor(basic_model, method = "pearson")

#percentnogocollegelog1p and percentacadnotimptlog1p are highly correlated, so one of them needs to be dropped. I will drop percentnogocollegelog1p.#

basic_model = select(basic_model, -c(percentnogocollegelog1p))

glimpse(basic_model)
```

##Basic Model - Demographic Variables
```{r Demographic Variables}
#setting up my dataset#

#Nickerson and Martens (2008) reocde procedure - combine mixed into moderate, and combined school into middle school# 

#This seems sensible to me too#

demographic_control <- df[, c("FR_SIZE", "STRATA", "FR_URBAN", "C0560", "C0562")]

colnames(demographic_control) <- c("school_size", "demographics", "urban", "crime_live", "crime_area")

demographic_control <- na.omit(demographic_control) #making sure that no NA values remain#

demographic_control$crime_live = ifelse(demographic_control$crime_live == 4, 2, demographic_control$crime_live)

demographic_control$crime_live_recode = 4 - demographic_control$crime_live #reverse-recoding crimelive#

table(demographic_control$crime_live) #checking recoding#
table(demographic_control$crime_live_recode) #checking recoding#

demographic_control$crime_area_recode = 4 - demographic_control$crime_area #reverse-recoding crimearea#

table(demographic_control$crime_area) #checking recoding#
table(demographic_control$crime_area_recode) #checking recoding#

#School Size needs no recoding
table(demographic_control$school_size)

(demographic_control <- demographic_control %>%
    mutate(school_type = case_when(
      demographics <= 143 ~ "Elementary",
      demographics >= 211 & demographics<=244 | demographics>=413 & demographics<=444 ~  "Middle_Combined",
      demographics>=311 & demographics<=344 ~ "High"
    )))

table(demographic_control$school_type)

#Rural or Urban (City, Suburb or Town)

demographic_control$urban = ifelse(demographic_control$urban == 4, 0, 1)

table(demographic_control$urban)

demographic_control = select(demographic_control, -c(demographics, crime_live, crime_area))

glimpse(demographic_control)
```

##Security Variables - Factor Analysis
```{r Security Variables}
#setting up my dataset#
security <- df[, c("C0110", "C0112", "C0114", "C0116", "C0120", "C0121", "C0122", "C0125", "C0129", "C0134", "C0136", "C0138", "C0140", "C0139", "C0141", "C0143", "C0142", "C0144", "C0146", "C0150", "C0153")]

colnames(security) <- c("visitor_badge", "control_building", "control_ground", "require_check", "random_check", "lock_inside", "close_lunch", "random_sweep", "drug_testing", "wear_uniform", "dress_code", "school_lockers", "book_bags", "panic_button", "emergency_notif", "anonymous_report", "student_id", "staff_id", "security_camera", "radio", "prohibit_phone")

security <- na.omit(security) #making sure that no NA values remain#

for (vars in colnames(security)){
  result = ifelse(security[[vars]] == 2, 0, 1)
  security[[vars]] = as.numeric(result)
}

student_factors_sec <- security[, c("random_check", "random_sweep", "drug_testing", "dress_code", "lock_inside", "close_lunch", "security_camera", "anonymous_report")]

management_factors_sec <- security[, c("visitor_badge", "emergency_notif", "radio", "control_building", "control_ground", "lock_inside", "close_lunch", "school_lockers", "panic_button", "security_camera", "staff_id", "anonymous_report","student_id", "book_bags", "prohibit_phone", "require_check", "wear_uniform")]

fa.parallel(student_factors_sec, cor='tet', fa = 'fa')

student_factors_sec_fa = fa(student_factors_sec, rotate = "oblimin", nfactors =4, cor='tet')

print(student_factors_sec_fa$loadings, cutoff = 0.3)

fa.parallel(management_factors_sec, cor='tet', fa = 'fa')

management_factors_sec_fa = fa(management_factors_sec, nfactors =3,cor='tet')

print(management_factors_sec_fa$loadings, cutoff = 0.3)

```

##Parental Community Variables - Factor Analysis
```{r Parental Community Variables}
#setting up my dataset#
parental_community <- df[, c("C0196", "C0198", "C0190", "C0192", "C0204", "C0206", "C0208", "C0210", "C0212", "C0214", "C0216", "C0218")]

colnames(parental_community) <- c("open_house", "parent_teacher_conf", "disciplinary_process", "parent_training_assist", "parenthelp_drug", "socialshelp_drug", "juvhelp_drug", "lawhelp_drug", "mhhelp_drug", "civichelp_drug", "privatehelp_drug", "relighelp_drug")

for (vars in colnames(parental_community[3:12])){
  result = ifelse(parental_community[[vars]] == 2, 0, 1)
  parental_community[[vars]] = as.numeric(result)
}

parental_community <- na.omit(parental_community) #making sure that no NA values remain#

glimpse(parental_community)

parental <- parental_community[3:5]

fa.parallel(parental, cor='tet', fa = 'fa') 

factor_parents = fa(parental, nfactors =1, cor = 'tet')

print(factor_parents$loadings, cutoff = 0.4)

community <- parental_community[6:12]

fa.parallel(community, cor='tet', fa = 'fa')

factor_community = fa(community, nfactors =3, cor='tet')

print(factor_community$loadings, cutoff = 0.4)
```

##Student Education Variables - Factor Analysis
```{r Student Education Variables}
#setting up my dataset#
student_education <- df[, c("C0174", "C0183", "C0176", "C0181", "C0175", "C0177", "C0179", "C0186")]

colnames(student_education) <- c("prevention_curriculum", "sel", "behav_mod", "mentoring", "peer_mediation", "student_court", "restorative_circles", "promote_community")

for (vars in colnames(student_education)){
  result = ifelse(student_education[[vars]] == 2, 0, 1)
  student_education[[vars]] = as.numeric(result)
}

student_education <- na.omit(student_education) #making sure that no NA values remain#

glimpse(student_education)

fa.parallel(student_education, cor='tet',fa = 'fa')

factor_student_ed = fa(student_education, nfactors =4, rotate = 'oblimin', cor='tet')

print(factor_student_ed$loadings, cutoff = 0.4)

print(factor_student_ed)
```

##FactoMineR Attempt
```{r cbind Dataset}
sub_sec_comm <- cbind(security, parental_community)

sub_sec_comm_ed <- cbind(sub_sec_comm, student_education)

for (vars in colnames(sub_sec_comm_ed[1:21])){
  sub_sec_comm_ed[[vars]] = as.factor(result)
}

for (vars in colnames(sub_sec_comm_ed[24:41])){
  sub_sec_comm_ed[[vars]] = as.factor(result)
}

glimpse(sub_sec_comm_ed)

library(FactoMineR)

res.mfa <- MFA(sub_sec_comm_ed, 
    group = c(21, 2, 3, 7, 8),
    type = c("n", "c", "n", "n", "n"),
    name.group = c("security", "parental_ord", "parental_cat", "community", "studented"),
    graph = F)

print(res.mfa)

library(factoextra)
ind <- get_mfa(res.mfa, "quali.var")

print(ind$coord)

```

##Loading into One Data.Frame 
```{r cbind Dataset}
sub1 <- cbind(basic_model, demographic_control)

sub2 <- cbind(sub1, security)

sub3 <- cbind(sub2, parental_community)

sub <- cbind(sub3, student_education)

glimpse(sub)
```


##Save Output of Preprocessing
```{r Output}

write.csv(sub,"/Users/kagenlim/Documents/GitHub/MA-Thesis/preprocessedstudy1.csv", row.names = FALSE)
```
 
```{r Descriptive Statistics}

descriptives <- sub[, c("total_incidents", "percentlowgrades", "percentgocollege")]

tocount <- sub[, c("r.randomsweeps", "r.prohibit_phone", "r.randommetal", "r.strictdresscode")]

tocount <- data.frame(tocount)

apply(tocount[-1], 2, table)

descriptives <- data.frame(descriptives)

library(stargazer)

stargazer(descriptives, covariate.labels = c("Total Incidents", "Percentage of Students with Low Grades", "Percentage of Students Unlikely to Attend College", "Random Sweeps in School", "Prohibition of Non-Academic Phone Use", "Random Metal Detector Checks on Students", "Strict Dress Code for Students"))

sub$t.total_incidents <- log1p(sub$total_incidents)

sub$t.percentlowgrades <- log1p(sub$percentlowgrades)

transform <- sub[, c("t.total_incidents", "t.percentlowgrades")]

transform <- data.frame(transform)

stargazer(transform, covariate.labels = c("Total Incidents", "Percentage of Students with Low Grades"))
```

```{r Save R Dataspace}

save.image(file = "my_work_space.RData")

```

